#!/usr/bin/python2
from datetime import date
from time import mktime, strptime
import sys
from crawler import crawl
from services import FireService
from argparse import ArgumentParser

parser = ArgumentParser(
    prog='crawler (open data)',
    usage='crawler --from-date=[FROM_DATE] --to-date=[TO_DATE]',
    description='Crawler script for fetching links with daily summary.'
)

parser.add_argument('--from-date', help='Start date for fetching. In YYYY-MM-DD format')
parser.add_argument('--to-date', help='End date for fetching. In YYYY-MM-DD format')

n = parser.parse_args(sys.argv[1:])

print('\n'.join(
    crawl(service=FireService,
          from_date=date.fromtimestamp(mktime(strptime(n.from_date, '%Y-%m-%d'))),
          to_date=date.fromtimestamp(mktime(strptime(n.to_date, '%Y-%m-%d')))
    )))